### ISSUE TITLE
Migrate from Material-UI v4 to MUI v5

### ISSUE THREAD

**Issue by LarsKemmann** [CareTogether/CareTogetherCMS#120]
See [migration guidance](https://mui.com/guides/migration-v4/). Please do follow the instructions in the guide and make small individual commits for each step, and test at each step along the way as well!

This upgrade will become increasingly important as we go forward with development, addressing bugs and getting us on a more stable (and supported!) UI library.

**Comment by DacoGT** [comment]
updates to package.json
-@material-ui/core": "^4.11.4", -->>"@mui/material": "^5.0.6",
-"@material-ui/icons": "^4.11.2", -->>"@mui/styles": "^5.0.2",
-"@material-ui/pickers": "^3.3.10", -->>"@mui/lab": "^5.0.0-alpha.53",

<Button color= 'default' no longer exists, change to 'primary'

**Comment by LarsKemmann** [comment]
It sounds like there's a question on whether we want to use styled-components vs. Emotion. Based on [comparing the two](https://github.com/jsjoeio/styled-components-vs-emotion) I have a hard time picking. The APIs are similar, the capabilities are similar. styled-components has the larger community and more polished project site, so it might be easier to find documentation for it. MUI on the other hand uses Emotion, and in either case it shouldn't be that hard to work with either library.

Do you have a preference? If not, all other things being equal I'd go with Emotion just because that's what the MUI team lists as their default.

**Comment by LarsKemmann** [comment]
Amazing what a couple of months will do -- there are now automatic "codemods" provided by the MUI team that fix most of the issues that were left open on this. I've created #325 to fix this.
