### ISSUE TITLE
All items completed for Host Family application, still shows as 'Prospective' and did not prompt for onboarding

### ISSUE THREAD

**Issue by AGNMM18** [CareTogether/CareTogetherCMS#156]
It shows the Corporal Punishment as incomplete, and it still lists them as a prospective HF

**Comment by LarsKemmann** [comment]
I think this might be a "works as designed" situation, with the actual problem being #155 - let's see if this continues to happen after that bug is fixed.

**Comment by LarsKemmann** [comment]
Yes, this was fixed with #155. 😊
