### ISSUE TITLE
Opting out, deactivating, or denying volunteer roles

### ISSUE THREAD

**Issue by simply-emily** [CareTogether/CareTogetherCMS#180]
At least for our org, we don't require children in the host home who are 18 or older (or other adults living in the home) to complete the training if they are not serving as volunteers. They only must complete background checks. Right now the system requires that we mark training as completed for all 18+ adults in the home.

**Comment by LarsKemmann** [comment]
It seems like the way to solve this is to provide an "opt-out" option for adults for any currently applicable volunteer family roles.

**Comment by LarsKemmann** [comment]
This is tracking work on request #186

**Comment by LarsKemmann** [comment]
Design notes from #97 copied here for reference.

-----

This will allow staff to, if needed, reject an application or temporarily place volunteers on a restricted hold.

**TODO:** Consider how to best add the `Reason` to the display output for a volunteer role (`VolunteerFamily` and `Volunteer` records).

## Requirements
1. Add the `Denied` enum member to `RoleApprovalStatus`.
2. Add the following `VolunteerFamilyCommand` overrides:
    ```c#
    public sealed record DenyVolunteerFamilyRole(Guid FamilyId, Guid UserId, DateTime TimestampUtc,
        string RoleName, string Reason)
        : VolunteerFamilyCommand(FamilyId, UserId, TimestampUtc);
    public sealed record ReinstateVolunteerFamilyRole(Guid FamilyId, Guid UserId, DateTime TimestampUtc,
        string RoleName, string Reason)
        : VolunteerFamilyCommand(FamilyId, UserId, TimestampUtc);
    ```
3. Add the following `VolunteerCommand` overrides:
    ```c#
    public sealed record DenyVolunteerRole(Guid FamilyId, Guid PersonId, Guid UserId, DateTime TimestampUtc,
        string RoleName, string Reason)
        : VolunteerCommand(FamilyId, PersonId, UserId, TimestampUtc);
    public sealed record ReinstateVolunteerRole(Guid FamilyId, Guid PersonId, Guid UserId, DateTime TimestampUtc,
        string RoleName, string Reason)
        : VolunteerCommand(FamilyId, PersonId, UserId, TimestampUtc);
    ```
4. Add the corresponding logic updates in `PolicyEvaluationEngine.CalculateVolunteerFamilyApprovalStatusAsync`
5. Unit tests
