### ISSUE TITLE
Volunteers UI

### ISSUE THREAD

**Issue by LarsKemmann** [CareTogether/CareTogetherCMS#19]

**Comment by LarsKemmann** [comment]
@DacoGT I pushed a bunch of updates since last night, building out the volunteers display. Editing isn't there yet, but you can see a flyout panel/drawer mini-demo on the "Volunteer Progress" screen when you open up the app. Take a look and let me know what you think! I'm planning to do some initial work to draft out (very) basic interactivity in that flyout so our alpha users can start entering volunteer info, and track volunteer approval status, starting Monday night.

**Comment by LarsKemmann** [comment]
@DacoGT My apologies for the late response. I've had a hard time keeping up with things this week and finally had a chance to review your comment and draft commits in more detail.

I've also been thinking about clean UI as well as accessibility. Right now the table structure works well, but I'm certainly keeping the collapse/expand concept in mind. I think there's potentially a lot of benefit to enabling a collapse/expand mode at some point for both the volunteer and referral tables. Would you be able to create an issue to document that? Then we can discuss it more there.

One issue with the volunteer form code - I'm glad you switched to using controlled components, but we'll also want to use the Material-UI components rather than just `<input>` elements.

I've got to step away for a couple of hours but then my plan is to add some basic form & dialog components to the volunteers drawer panel this afternoon & evening. If you're planning to do some more coding today or tomorrow, reach out to me on Teams so we can coordinate. A good place to start might be applying the same UI layout that I created for the Volunteers UI to the Referrals UI.

**Comment by DacoGT** [comment]
@LarsKemmann I can certainly do some issue creation. I'll jump into that tonight. The main purpose on my branch was to start digging in and perhaps give you some useful snippets to pluck from. I'm struggling to get the time to sit and produce in a meaningful way. It's funny how much different 8 hours a day, 5 days a week feels when comparing to twice a week for just a couple hours. I'm determined to find a way to get you a leg up.

I'm planning to spend some time tonight updating to your latest, working that issue you mentioned and coding some more. If you you're available for a chat I'm planning to start about 8:30/9:00 eastern.

**Comment by LarsKemmann** [comment]
I think creating the issue for expanding/collapsing might be moot at this point. Take a look at the latest and you'll see what I mean. 😊

Yes, once you update let's talk about what you can do next! I'll be online.

**Comment by LarsKemmann** [comment]
Closing this issue because it's really too broad to be useful.
