### ISSUE TITLE
Upgrade React Router from v5 to v6

### ISSUE THREAD

**Issue by LarsKemmann** [CareTogether/CareTogetherCMS#202]
https://reactrouter.com/docs/en/v6/upgrading/v5

**Comment by fhdaax** [comment]
I'd like to take this over.

**Comment by LarsKemmann** [comment]
That would be amazing! Thank you @fhdaax! Feel free to submit a PR; if you want to create a draft one first, I'll assign the issue to you and link it to the PR.
