### ISSUE TITLE
Having to re-do at the individual level some family-level approval policies

### ISSUE THREAD

**Issue by simply-emily** [CareTogether/CareTogetherCMS#254]
Currently if an individual is approved as a HF and then wants to serve in an individual role (such as Family Coach) we have to re-check off approval items such as confidentiality agreement, statement of faith, references, etc. Is there a way to be able to avoid this if items are one-time approval items for all roles to avoid so much repeat data entry?

**Comment by LarsKemmann** [comment]
To address this, we need an approval policy field that lets some requirements be "inherited" from the family level, if they have been completed for the family. This needs to be opt-in per requirement.

**Comment by LarsKemmann** [comment]
This is being closed as won't-fix for now. The plan is for policies to be updated to require items at a per-participant or per-adult level, and do the corresponding data update work.

This feature could be revisited in the future if a specific need for it is identified that can't be adequately met by policy changes.
