### ISSUE TITLE
Switch from Yarn to NPM to simplify developer setup

### ISSUE THREAD

**Issue by LarsKemmann** [CareTogether/CareTogetherCMS#324]
Includes:

- [ ] yarn.lock replacement
- [ ] CI/CD workflow updates
- [ ] README.md updates

**Comment by RishiKumarRay** [comment]
can you give any context on how to update

**Comment by LarsKemmann** [comment]
@RishiKumarRay You can google "how to switch from yarn to npm" to get more help with the steps, but here's a start:
https://stackoverflow.com/questions/51239726/react-native-switch-from-yarn-to-npm

The GitHub actions files in the `.github/workflows` directory also need to be updated so that the CI/CD builds use NPM instead of yarn.
