### ISSUE TITLE
Hide canceled arrangements from view (with option to show)

### ISSUE THREAD

**Issue by LarsKemmann** [CareTogether/CareTogetherCMS#437]
Currently, all arrangements - including canceled arrangements - are shown on the partnering family screen. This can create visual clutter when one or more canceled arrangements are mixed in with active arrangements. Move the canceled arrangements out of the primary display logic, and hide them behind an [`<Accordion />`](https://mui.com/material-ui/react-accordion/) (before the "New Arrangement" buttons) that, when collapsed, shows the number of canceled arrangements.

https://github.com/CareTogether/CareTogetherCMS/blob/d1c5fa07f344b0e63b90567a776c9f1f019f1e1b/src/caretogether-pwa/src/Components/Referrals/PartneringFamilyScreen.tsx#L278-L298

**Comment by donschaefer** [comment]
@LarsKemmann  - although you've included the relevant lines of code to investigate (enabling someone to possibly provide a code fix without necessarily reviewing the changes they've made in a browser), it'd be helpful if you could provide a link and/or repro steps for navigating to this UI within the app.

Looking through the main screens I'm seeing, nothing is jumping out at me as to where I might find "arrangements" (or what they are for that matter... though this might make much more sense to someone who is already familiar with the organization)

**Comment by donschaefer** [comment]
Looking into this one

**Comment by LarsKemmann** [comment]
@donschaefer You guessed almost what I had intended with interpretation "A", and thanks for thinking it through more thoroughly than I did. 😊 What I had envisioned was, instead of a new section, to simply create a new block within the Masonry component (before the block of "New Arrangement" buttons) that is a collapsed list of cancelled arrangements. However, what I didn't think through was that expanding that accordion would then not tile nicely with the rest of the masonry blocks.

After thinking about it more, and considering the direction I'd like the overall UX to go in the future, the condensed approach (B) is superior. Let's go with that.

**Comment by LarsKemmann** [comment]
This enhancement is now live. Many thanks to @donschaefer for your help on this!!

**Comment by simply-emily** [comment]
@donschaefer This is so helpful! This will really declutter the view of the families that we're serving, especially the ones that have more complex needs or several children. Thank you! 😊

**Comment by donschaefer** [comment]
No problem, happy to help out! :)
