### ISSUE TITLE
Combine the three volunteer table formats into a single Volunteers screen

### ISSUE THREAD

**Issue by LarsKemmann** [CareTogether/CareTogetherCMS#47]
Use the [Button Group](https://material-ui.com/components/button-group/) component to toggle between the three display modes:
 - Approval
 - Applications
 - Progress

The button group should be in the app bar area -- which means the app bar will need to be rendered as part of the page rather than as part of the global _App.tsx_ component.

This will simplify navigation and make the app more mobile-friendly as well.

**Comment by DacoGT** [comment]
@LarsKemmann Some questions:

1. This is different than the Referrals, Volunteers, Applications, and Progress using Routes and Drawer setup in App.tsx correct?
2. There currently isn't a VolunteerApproval component. Should a basic version be included in this task? Or is the Volunteer component going to be the VolunteerApproval?
3. The new combined component should contain a new AppBar in addition to the one in App.tsx?
4. How does this change the routing design? Does volunteerApplications and volunteerProgress merge into something else?

**Comment by LarsKemmann** [comment]
@DacoGT This will actually replace the current menu/bottom-nav options. 😊 The idea is that both left nav and bottom nav will show the following options:
1. Dashboard <or Home>
2. Referrals
3. Volunteers
4. <more to be added in the future, e.g. Communities>

Then within the Volunteers screen (which will be a new component named Volunteers.tsx, replacing the current one), we'll update the top App Bar to include a button group that has three options which control the contents of the screen:
1. Approval - Volunteers.tsx --> rename this to VolunteerApproval.tsx
2. Applications - VolunteerApplications.tsx
3. Progress - VolunteerProgress.tsx
So the new Volunteers.tsx is just an app bar+button group+wrapper around those three choices, basically. We'll want it to support routing as well, so the new routes will look like:
1. <host>/volunteers/approval - the default if the user only provides /volunteers
2. <host>/volunteers/applications
3. <host>volunteers/progress
