### ISSUE TITLE
Arrangements can be ended before they started

### ISSUE THREAD

**Issue by LarsKemmann** [CareTogether/CareTogetherCMS#524]
**NOTE: This is a priority issue because triggering this bug will actually cause corruption of the data model that requires an administrator to fix the stored data in the back-end; the application will not be able to load records for an organization & location once the bug has been triggered for that organization & location.**

To reproduce this issue in your local development environment:

1. Open the Doe Family (`http://localhost:3000/org/11111111-1111-1111-1111-111111111111/22222222-2222-2222-2222- 222222222222/families/11111111-1111-1111-1111-111111111111`)
2. Add all required volunteer assignments to one of the arrangements, and complete (or exempt) all setup requirements, so that the arrangement shows as ready to start. Example:
   ![image](https://user-images.githubusercontent.com/5834429/233754672-55e8973c-01da-4ee5-9225-580c41d0e0a4.png)
3. **Start** the arrangement on a given date, e.g., April 21, 2023. Note that, currently, starting an arrangement will cause it to move down below any arrangements that are still in the "Setting up" stage.
   ![image](https://user-images.githubusercontent.com/5834429/233754760-b3d3aec2-53a0-4194-a9ae-4ae66c2e8eac.png)
4. Attempt to **end** the arrangement on an earlier date than the start date, e.g., April 1, 2023.
5. In the developer console, notice that a 500 error occurs with the following message in the payload:
   > `System.ArgumentException: All timeline stages must have start dates before their end dates. ...`

**NOTE: Once the bug has been triggered, all further attempts to load or edit data for that organization & location will fail. In the local development environment, you can simply stop & restart the debugger to reset the data to the known good starting point.**

The fix for this is to edit the code for the `DateTimePicker` in the `EndArrangementDialog` to restrict date inputs to only dates (& times) that are *after* the start date+time of the arrangement. The [DateTimePicker validation documentation](https://mui.com/x/react-date-pickers/validation/) will be helpful for this.

**Comment by LarsKemmann** [comment]
This should be a straightforward restriction on the EndArrangement form

**Comment by LarsKemmann** [comment]
A more in-depth fix would be to implement deeper server-side validation, but that is part of a larger future effort that's outside the scope of this issue. Extra credit if you wish to implement server-side validation for this particular issue as well :) -- if so, look into the `ReferralModel.cs` file.

**Comment by Ad-Mortem** [comment]
Working on this

**Comment by Amanda9797** [comment]
Thank you so much @Ad-Mortem!! We are so grateful!
