### ISSUE TITLE
Ability to delete families

### ISSUE THREAD

**Issue by Amanda9797** [CareTogether/CareTogetherCMS#630]

**Comment by AGNMM18** [comment]
We have duplicates that need deleted

**Comment by LarsKemmann** [comment]
Individual people can already be deleted (click the 'edit' pencil on the person's card and use the 'Delete' option at the bottom of the dialog that opens up) but the same thing needs to be possible for families (partnering families as well as volunteer families). This does raise some potentially-tricky questions about whether to allow this if that family has previously been linked to an arrangement or community, but for now I'm going to go ahead and implement this on the assumption that that will be a very rare issue.
