### ISSUE TITLE
Logging into the CMS - Issue

### ISSUE THREAD

**Issue by AGNMM18** [CareTogether/CareTogetherCMS#631]
![image](https://user-images.githubusercontent.com/92525893/236860854-ef0a06e2-2605-4120-be1b-cf92f7ae2c5d.png)

When logging into the CMS, the screen 'Attempting to Migrate a suspected old link' appears, did not redirect but had to refresh the screen.  5.8.23 submitted at 10:30 AM

**Comment by LarsKemmann** [comment]
I *think* this particular issue was the result of a backend error that I fixed shortly afterwards. Closing this for now; @AGNMM18 please let me know if it comes up again!
