### ISSUE TITLE
Show the # of upcoming scheduled (monitoring) requirements in a separate badge from the # of missing requirements

### ISSUE THREAD

**Issue by LarsKemmann** [CareTogether/CareTogetherCMS#646]
The user interface is designed to alert the user to missed requirements on arrangements, and it currently does so using the ❌ "icon" regardless of whether an incomplete requirement is actually past-due or not.

In this example, two past-due requirements and one upcoming requirement are grouped together as the "3" badge on the ❌ "icon":

![Image](https://user-images.githubusercontent.com/5834429/242379352-cde9780e-17bb-47b3-8a8b-8692ac72a36a.png)

Instead of grouping incomplete and upcoming requirements like this, use the 📅 "icon" to show upcoming-but-not-yet-past-due requirements in their own badge. This will make the user interface much friendlier for end users who are trying to determine whether they are up-to-date on everything that is needed from them.

**Comment by jaysengardner** [comment]
working on it!
