### ISSUE TITLE
Remove/Refactor Columns to Improve Readability

### ISSUE THREAD

**Issue by donschaefer** [CareTogether/CareTogetherCMS#714]
1. Combine first/last name columns
2. Remove "Gender" & "Age" columns
3. Make family names bold
4. Combine All remaining columns into a single "Roles" column that extends the remaining width of the page. Within that column, "Host Family" role/status should be displayed at the family level & all other roles/statuses should be displayed in a row that wraps to additional lines (thus extending the height of the row itself) when necessary (i.e. when there are many roles present and/or too little room to display them all on a single row due to device width restrictions)
5. Add two filter menus above the volunteers table: Roles and Statuses. The Roles filter gets applied first. Both filters are logical ORs of their options, and both filters have a 'Not Applied' option. The Statuses filter will apply just to the filtered subset of Roles.

**Comment by donschaefer** [comment]
@LarsKemmann - While I do appear to have the ability to create an issue, I lack the ability to...

1. Create Labels / "Anyone with write access to a repository" - https://docs.github.com/en/issues/using-labels-and-milestones-to-track-work/managing-labels#creating-a-label)
2. Apply Labels / "Anyone with triage access to a repository can apply and dismiss labels" - https://docs.github.com/en/issues/using-labels-and-milestones-to-track-work/managing-labels#applying-a-label

With that said, I'll hold off on creating additional issues for the time being & circle back later when additional permissions are available

**Comment by LarsKemmann** [comment]
> @LarsKemmann - While I do appear to have the ability to create an issue, I lack the ability to...
> 
> 1. Create Labels / "Anyone with write access to a repository" - https://docs.github.com/en/issues/using-labels-and-milestones-to-track-work/managing-labels#creating-a-label)
> 2. Apply Labels / "Anyone with triage access to a repository can apply and dismiss labels" - https://docs.github.com/en/issues/using-labels-and-milestones-to-track-work/managing-labels#applying-a-label
> 
> With that said, I'll hold off on creating additional issues for the time being & circle back later when additional permissions are available

I think I fixed it, try again?

**Comment by LarsKemmann** [comment]
I just realized that this issue will need to be paired with an update to how we do filtering on this screen for the different roles. For now, maybe the easiest is to just have a two level nested menu for filtering Roles? I want to give that some more thought though.

**Comment by donschaefer** [comment]
> I just realized that this issue will need to be paired with an update to how we do filtering on this screen for the different roles. For now, maybe the easiest is to just have a two level nested menu for filtering Roles? I want to give that some more thought though.

Np @LarsKemmann - I will move this back to the "Ideas" column until there's a clear plan as to how this should be moved forward & whether or not there should be any follow-up items (in the event we want to tackle this change in phases)

**Comment by donschaefer** [comment]
> > I just realized that this issue will need to be paired with an update to how we do filtering on this screen for the different roles. For now, maybe the easiest is to just have a two level nested menu for filtering Roles? I want to give that some more thought though.
> 
> Np @LarsKemmann - I will move this back to the "Ideas" column until there's a clear plan as to how this should be moved forward & whether or not there should be any follow-up items (in the event we want to tackle this change in phases)

On second thought @LarsKemmann, given that...
1. This particular decision only has to do with item # 4 on the list above
2. You've expressed an urgency to getting these changes made
3. There are no other items that you've asked me to work on this week
... I'll work on changes # 1 - 3 above, post a PR for it & then let you decide if you'd like to go with an incremental approach that addresses # 4 in one or more future PRs or if you'd like to keep the PR on hold until we hash # 4 out to your satisfaction.

Hopefully this approach will be okay, but if not, please ping me asap

**Comment by donschaefer** [comment]
@LarsKemmann - PR posted @ https://github.com/CareTogether/CareTogetherCMS/pull/723 for action items # 1-3. Moving this to the "On Hold" column while you review the PR & determine if/how you'd like item # 4 to be addressed in conjunction with this issue or if you'd like to separate that one out for future development.

**Comment by LarsKemmann** [comment]
I think it's important enough to address # 4 that we should keep it as part of the same PR.

After some review, here's how I'd like the filters to work:

1. Create two separate filter menus, one for roles and one for statuses.
2. Change the filter logic to the following:
  a. The filters should start disabled by default. The user can select one or more options in a filter's menu to enable it, and once enabled there's an option to "clear" the filter which disables it again.
  b. When only the roles filter is enabled, filter to only include families where the family and/or individuals have at least one of the selected roles, at any status other than null/undefined.
  c. When only the statuses filter is enabled, filter to only include families where the family and/or individuals have at least one of the selected statuses across any of their roles.
  d. When both filters are enabled, the family and/or individuals have to have at least one of the selected roles *and* that role has to be at one of the selected statuses. So if I select family coach and host family, and approved and onboarded, then an onboarded ministry coordinator who is only at prospective for host family would be excluded.

**Comment by donschaefer** [comment]
> I think it's important enough to address # 4 that we should keep it as part of the same PR.
> 
> After some review, here's how I'd like the filters to work:
> 
> 1. Create two separate filter menus, one for roles and one for statuses.
> 2. Change the filter logic to the following:
>    a. The filters should start disabled by default. The user can select one or more options in a filter's menu to enable it, and once enabled there's an option to "clear" the filter which disables it again.
>    b. When only the roles filter is enabled, filter to only include families where the family and/or individuals have at least one of the selected roles, at any status other than null/undefined.
>    c. When only the statuses filter is enabled, filter to only include families where the family and/or individuals have at least one of the selected statuses across any of their roles.
>    d. When both filters are enabled, the family and/or individuals have to have at least one of the selected roles _and_ that role has to be at one of the selected statuses. So if I select family coach and host family, and approved and onboarded, then an onboarded ministry coordinator who is only at prospective for host family would be excluded.

Hey @LarsKemmann when I initially reviewed this email, it wasn't making sense to me, so I thought "let me circle back & read this again while I have the application side-by-side with the email to see if it makes more sense with some additional focus/context. However, even with that, I'm still finding myself a bit confused as the only filters I'm seeing are status filters for the volunteer roles, but it doesn't look like there are any filters for the roles themselves (at least from what I can currently see visually & a little bit of poking around the code). I suspect this may make more sense with one of the following...
1. Increased familiarity with the application 
2. The presence of a LOT more test data
3. Possibly a higher level of access than what the test account may be providing
4. A screenshare with you

Given that we've got another call scheduled tomorrow night, I think #4 would likely be the most efficient approach (and may offer some opportunity to handle additional questions/considerations that may come up), so hopefully we can touch on this tomorrow night.

**Comment by LarsKemmann** [comment]
Sounds good. In the meantime, just to clarify, there is currently no separate filter for the roles. So this would actually be adding functionality. Right now, the separate columns for each role sort of function as role filters, though they don't do that very well.

**Comment by LarsKemmann** [comment]
Marking this as completed now that #723 is merged. I've opened #730 to track one unforeseen (non-critical) issue that came up during testing.
