### ISSUE TITLE
Add ability to delete a family

### ISSUE THREAD

**Issue by donschaefer** [CareTogether/CareTogetherCMS#719]

**Comment by donschaefer** [comment]
@LarsKemmann - While I've added this issue here since it was on my list of UX recommendations to consider & you had asked that I add those recommendations to this board, this issue...
1. appears to already be getting tracked @ https://github.com/CareTogether/CareTogetherCMS/issues/630 & 
2. while related to UX, is largely not something that would be considered "UI" work
... so it may be appropriate to remove/close this issue

**Comment by LarsKemmann** [comment]
That's very true, I'll close this as a duplicate. Thanks!
