### ISSUE TITLE
Weekly UX Review

### ISSUE THREAD

**Issue by donschaefer** [CareTogether/CareTogetherCMS#724]
**Issue Description:**
Spend up to 90min/week conducting a UX review of the CareTogether application & documenting the ideas that come out of those review sessions as GitHub "Issues" in the "Ideas" column of this "UX/UI Improvements" project until the entirety of the application has been reviewed. 

As new areas of review are started, add a corresponding empty checkbox to this issue description to denote that a review of a particular area has been started. When the corresponding review is completed, check the checkbox.

- [ ] Volunteers 
- [x] Volunteers > Progress Tab
- [x] Volunteers > Approvals Tab
- [x] Volunteers > Create New Family
- [ ] Volunteers > Family Details
- [ ] Referrals
- [ ] Referrals > Family Details

**Comment by LarsKemmann** [comment]
All great questions.

1. Yes.
2. New issues, and add them to the leftmost column of the UX/UI Improvements project.
3. Extend the time to a total of 90 minutes max per week to account for creating the issues.
4. Let's use this issue to track a single pass through each part of the app. That way you can use tasks to track the parts you've already reviewed.

**Comment by donschaefer** [comment]
@LarsKemmann  - Moving the original issue description down to this comment, as that's what it likely should have been to begin with & I figured it might be good to save the context rather than just deleting it.

**Original Issue Description (For Historical Context)**
@LarsKemmann - Adding this to the board so that we can track it & modify as needed since you had expressed an interest in doing a time-boxed 1hr UX review on an ongoing basis.

Before I do any additional reviews though, I think it would be good to update this issue with specifics outlining the following:
1. **Am I correct in recalling that you want these reviews time-boxed to 1hr/week?**
2. **In what format would you like the review delivered?** _Teams chat (as done previously), response on this issue's discussion thread, creation of new GitHub issues, or something else?_
3. **If you would like new GitHub issues created as part of this work...** _should the time spent reviewing be decreased to ensure the 1hr time-box is closely adhered to, or would you prefer to increase the time-box (and if so, to what)?_
4. **How would you like completion of this issue to be determined?** _No completion (truly on-going until you move this issue to "Closed")? When all areas of the site have been reviewed once?  When a certain amount of total hours have been spent? Something else?

**Comment by LarsKemmann** [comment]
Let's for now just track ideas in Additional Ideas and mark them off as we start developing them, since we're in an ideation stage.
