### ISSUE TITLE
Communities on Family Screen

### ISSUE THREAD

**Issue by donschaefer** [CareTogether/CareTogetherCMS#739]
...Start thinking about a better design for the family screen. As an initial starting point, I would like to actually make the screen "worse" (by adding even more information) before we make it better, so we can see more of the behavior and functionality that the screen actually needs to expose before we decide how to optimize it. Specifically, there are two things I would like to see happen on the family screen:

**Action Item:**
> * allow the user to see a list of which communities the family has been added to. This is basically the counterpart to how you can view member families from the community screen. This should be a quick one to implement, and as an FYI, I don't expect most families to ever have more than one community that they are a part of. So you can absolutely optimize for that case.

**Additional Action Item (_that has since been moved to #741_):**
> * allow the user to see a list of past referrals and select one referral to view the details of, with the most recent referral being the default.

If you could start on the display of communities, ideally with the community being linked to navigate to the community screen (like the family is linked to the family screen on the community screen), that would be fantastic. I've had several requests for that over the past 2 weeks.

(Originally posted @ https://github.com/CareTogether/CareTogetherCMS/issues/722#issuecomment-2078430716)

**Comment by LarsKemmann** [comment]
Renaming this issue to clarify that it's solely focused on adding the new Communities section to the family screen
